In [1]:
#importing Modules
import numpy as np
import pandas as pd

In [2]:
#mount google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
#read train.csv from my drive data folder
file_path = '/content/drive/My Drive/data/train.csv'
df = pd.read_csv(file_path)

In [4]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
df.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

1. Creating a numpy array
#Empty Array


In [6]:
a = np.empty((3,4))

In [7]:
#Random values are initialized
a

array([[4.64575749e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

Creating numpy array from array

In [8]:
arr = np.array([3,4,5,6])
print(arr.shape)

(4,)


In [9]:
arr

array([3, 4, 5, 6])

2D array

In [10]:
arr_2d = np.array([[1,2,3],[4,5,6]])

In [11]:
arr_2d.shape

(2, 3)

In [12]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

#Checking the dimension of the array

In [13]:
arr_2d.ndim

2

In [14]:
arr_2d.shape


(2, 3)

In [15]:
#reshaping the array
#It converts the array in row-first order
arr_2d.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
arr_1 = arr_2d.reshape(-2,3)

In [17]:
# Assume arr_2d is a 2D array (e.g., a numpy array).
# Reshape the 2D array `arr_2d` into a new array `arr_1` with a specific shape.
# The '-2' indicates that the reshaping should infer one of the dimensions
# based on the original array's size, and the '3' specifies that the second
# dimension should have 3 elements.
# The '-2' value will automatically determine the appropriate dimension size
# that allows the reshape operation to be valid.

arr_1

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [19]:
arr_2d.ndim

2

In [20]:
#finding the size of each element in bytes
print(arr.dtype)
arr_2d.itemsize  #in bytes

int64


8

## Matrices

In [21]:
zeros = np.zeros((3,2))

In [22]:
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
ones = np.ones((2,3))

In [24]:

ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
#Initializing matrices with some constant value
a = np.full((3,2),2)

In [26]:
a

array([[2, 2],
       [2, 2],
       [2, 2]])

## Identity matrix; diagonal is one and rest elements are zeros


In [27]:
order = 3
b = np.eye(order)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#Indexing and Slicing


In [28]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
#Indexing
c[0]

array([1, 2, 3])

In [30]:
c[0][0]

1

In [31]:
#Slicing
c[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [32]:
#All rows; excluding the first element
c[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [33]:
#last row
c[-1]

array([7, 8, 9])

In [34]:
c[-1][-1]

9

In [35]:
c[:,-2:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [36]:
#Looping over a matrix
for x in c:
  print(x)

[1 2 3]
[4 5 6]
[7 8 9]


In [37]:
for x in np.nditer(c):
  print(x)

1
2
3
4
5
6
7
8
9


In [38]:
#Without using nditer
for row in c:
  for x in row:
    print(x)

1
2
3
4
5
6
7
8
9


## Linspace: evenly spaced elements (The start and end values are inclusive)

In [39]:
d = np.linspace(1,100,10)
print(d.shape)
d

(10,)


array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [40]:
#floating point values
e = np.linspace(1,45,6)
print(e.shape)
e

(6,)


array([ 1. ,  9.8, 18.6, 27.4, 36.2, 45. ])

## Arange: The end element are exclusive

In [41]:
f = np.arange(1,100,3)

In [42]:
f.shape

(33,)

In [43]:
f

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [44]:
#in reverse order
g = np.arange(100,2,-5)

In [45]:
g.shape

(20,)

In [46]:
g

array([100,  95,  90,  85,  80,  75,  70,  65,  60,  55,  50,  45,  40,
        35,  30,  25,  20,  15,  10,   5])

# Random number Generation

In [47]:
a = np.random.randint(5)

In [48]:
a

4

In [49]:
a = np.random.randint(low = 11, high = 52)

In [50]:
a

29

#Generating array

In [51]:
arr = np.random.randint(7,45,(3,3))

In [52]:
arr

array([[26, 32, 12],
       [ 9,  7, 22],
       [23, 26, 22]])

In [53]:
#Random number between 0 and 1
arr = np.random.random(2)

In [54]:
arr

array([0.47501547, 0.27348315])

In [55]:
arr_2d = np.random.random((3,3))

In [56]:
arr_2d

array([[0.48929345, 0.46077795, 0.31502278],
       [0.90720919, 0.00340159, 0.62540257],
       [0.60984888, 0.41822681, 0.86421549]])

In [57]:
#Uniformity among values
low = 1
high = 10
a = np.random.random((2,2))
a = low + a*(high-low)
a

array([[8.76257172, 2.97183075],
       [8.80919914, 8.31341338]])

In [58]:
#using uniform function
a = np.random.uniform(low, high,(2,2))

In [59]:
a

array([[5.47320199, 1.51882982],
       [3.39586513, 6.78754432]])

In [60]:
#Random numbers belonging to Normal (Gaussian) distribution
a = np.random.randn(2,2)
b = np.mean(a)
var = np.var(a)
print(b,var)
a

0.16432356312488972 1.3775250275453832


array([[ 2.06358571, -1.01832981],
       [ 0.1577793 , -0.54574095]])

In [61]:
a = np.random.normal(2,.5,(2,3))
b = np.mean(a)
c = np.var(a)
print(b,c)
a

1.6204648815947167 0.37166223825383576


array([[1.73012215, 0.72285203, 1.77399216],
       [1.33003896, 1.42083294, 2.74495105]])

# Matrix Operations

In [62]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [63]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
#Transpose
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [65]:
#Multiplicative Inverse
a = np.array([[1,2],[4,6]])

a_inv = np.linalg.inv(a)


In [66]:
a_inv

array([[-3. ,  1. ],
       [ 2. , -0.5]])

In [67]:
#Matrix Multiplication
np.matmul(a,a_inv)

array([[1., 0.],
       [0., 1.]])

In [68]:
a

array([[1, 2],
       [4, 6]])

In [70]:
b = a.T

In [71]:
#Matrix Addition
a + b

array([[ 2,  6],
       [ 6, 12]])

In [72]:
#Matrix Subtraction
a - b

array([[ 0, -2],
       [ 2,  0]])

In [73]:
#Matrix Multiplication (element to element)
a * b

array([[ 1,  8],
       [ 8, 36]])

In [74]:
#for matrix multiplication we need to use matmul()
np.matmul(a,b)

array([[ 5, 16],
       [16, 52]])

In [77]:
#Division
div = np.matmul(a,np.linalg.inv(b))

In [78]:
div

array([[-1.,  1.],
       [-6.,  5.]])

In [80]:
#Arithmetic operation of matrix with a scalar
a = np.array([1,2,3,4,5])
#Addition
a+10

array([11, 12, 13, 14, 15])

In [81]:
#subtraction
a-10

array([-9, -8, -7, -6, -5])

In [82]:
#Scalar Multiplication
a*10

array([10, 20, 30, 40, 50])

In [83]:
#Scalar Division
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [84]:
#Squaring
a*a

array([ 1,  4,  9, 16, 25])

In [85]:
a+a #2*a

array([ 2,  4,  6,  8, 10])

### Complex Mathematical Operation

In [86]:
#log
a = 2.34
b = np.log(a)
b

0.85015092936961

In [87]:
a = [1,2,3,4,5,6]
b = np.log(a)
b

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947])

In [88]:
#Exponential
a = np.log(2)
b = np.exp(a)
b


2.0

In [89]:
a = [np.log(a) for a in range(1,5)]
b = [np.exp(i) for i in a]
b

[1.0, 2.0, 3.0000000000000004, 4.0]

#Sin, Cos, Tan

In [90]:
factor = [1,2,3,4]
rad = [np.pi/a for a in factor]

sins = [np.sin(rad)]
cos = [np.cos(rad)]
tan = [np.tan(rad)]

In [92]:
sins

[array([1.22464680e-16, 1.00000000e+00, 8.66025404e-01, 7.07106781e-01])]

In [93]:
cos

[array([-1.00000000e+00,  6.12323400e-17,  5.00000000e-01,  7.07106781e-01])]

In [94]:
tan

[array([-1.22464680e-16,  1.63312394e+16,  1.73205081e+00,  1.00000000e+00])]

## Statistics

In [95]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [96]:
mat.min()

1

In [97]:
mat.max()

9

In [98]:
mat.min(axis=0)

array([1, 2, 3])

In [99]:
mat.min(axis=1)

array([1, 4, 7])

In [100]:
#Mean
mat.mean()

5.0

In [101]:
mat.mean(axis=1)

array([2., 5., 8.])

In [102]:
mat.mean(axis = 0)

array([4., 5., 6.])

In [103]:
#Variance
mat.var()

6.666666666666667

In [104]:
mat.var(axis= 0)

array([6., 6., 6.])

In [105]:
mat.var(axis= 1)

array([0.66666667, 0.66666667, 0.66666667])

In [106]:
#Standard deviation
mat.std()

2.581988897471611

In [107]:
mat.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [108]:
mat.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [110]:
#Concatenating numpy arrays
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])


In [111]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [112]:
np.concatenate((a,b),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [113]:
#Using hstack and vstack
np.hstack([a,b])



array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [115]:
np.vstack([a,b])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
Credit: Kaggle: Raj Mehrotra